### ISSUE TITLE
Branch B does not launch with Binder

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/CompEnv-Ex3#1]
Branch B is currently breaking a Binder launch. Suspect we'll have to pin python runtime.

PRs #2 and #3

**Comment by sgibson91** [comment]
Binder error message:
```
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (setup.py): started
  Building wheel for scikit-learn (setup.py): finished with status 'error'
  ERROR: Complete output from command /srv/conda/envs/notebook/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-pfwil6kx/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7b2kz789 --python-tag cp37:
  Running setup.py clean for scikit-learn
  ERROR: Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 168, in get_numpy_status
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  Traceback (most recent call last):
    File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 148, in get_scipy_status
      import scipy
  ModuleNotFoundError: No module named 'scipy'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 269, in <module>
      setup_package()
    File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 249, in setup_package
      .format(numpy_req_str, instructions))
  ImportError: Numerical Python (NumPy) is not installed.
  scikit-learn requires NumPy >= 1.8.2.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
Installing collected packages: numpy, pytz, pandas, cycler, kiwisolver, pyparsing, matplotlib, scikit-learn, scipy, mlxtend
  Running setup.py install for scikit-learn: started
    Running setup.py install for scikit-learn: finished with status 'error'
    ERROR: Complete output from command /srv/conda/envs/notebook/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-pfwil6kx/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qn7qme3l/install-record.txt --single-version-externally-managed --compile:
    ERROR: Partial import of sklearn during the build process.
    Traceback (most recent call last):
      File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 148, in get_scipy_status
        import scipy
    ModuleNotFoundError: No module named 'scipy'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 269, in <module>
        setup_package()
      File "/tmp/pip-install-pfwil6kx/scikit-learn/setup.py", line 259, in setup_package
        .format(scipy_req_str, instructions))
    ImportError: Scientific Python (SciPy) is not installed.
    scikit-learn requires SciPy >= 0.13.3.
    Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html

    ----------------------------------------
ERROR: Command "/srv/conda/envs/notebook/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-pfwil6kx/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qn7qme3l/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-pfwil6kx/scikit-learn/
Removing intermediate container da8a23fd0fb8
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"' returned a non-zero code: 1
```

**Comment by sgibson91** [comment]
Adding a `runtime.txt` pinning Python to version 3.6 fixes the broken Binder build of `branch-b` (see PR #2).
I tried adding the same to `branch-a` for consistency (PR #3), but this causes an error in the notebook - see https://github.com/alan-turing-institute/CompEnv-Ex3/pull/3#issuecomment-499777318.

My guess is that this is due to `scikit-learn` being pinned as `>=0.19.1` in `requirements.txt` in `branch-a`.
https://github.com/alan-turing-institute/CompEnv-Ex3/blob/5443965c81165464865679be1aae3b98c7ced81a/requirements.txt#L4

There has probably been a further release on PyPI that is now being pulled by `pip` causing the deprecation of the `n_iter` keyword to `Perceptron`. I will investigate whether leaving `branch-a` to install Python 3.7 (that is to say, no `runtime.txt` file) still produces the same difference we want. Otherwise, I think we will have to change the pinning of `scikit-learn` in `requirements.txt` (and include `runtime.txt`).

**Comment by sgibson91** [comment]
~~To see the bug in `branch-a` with the `runtime.txt` file, launch this binder:
https://mybinder.org/v2/gh/sgibson91/CompEnv-Ex3/branch-a?filepath=chap03.ipynb~~

[No longer produces the bug]

**Comment by sgibson91** [comment]
The bug in `branch-a` is also occurring on the `alan-turing-institute` hosted binder too. I think the `n_iter` argument to `Perceptron` has been deprecated between scikit-learn versions 0.20 and 0.21. Therefore, we should add a `runtime.txt` file to `branch-a` _and_ change line 4 in the `requirements.txt` (on `branch-a`) to:
```
scikit-learn>=0.19.1,<0.21.*
```

See PyPI for release history: https://pypi.org/project/scikit-learn/#history

**Comment by sgibson91** [comment]
> ```
> scikit-learn>=0.19.1,<0.21.*
> ```

This worked, I've now recovered the original behaviour of the notebooks 🎉
